import type { Knex } from "knex";

/**
 * Content Publishing Pipeline: published_content table
 *
 * Stores blog posts and articles generated by the CMO Agent
 * or created manually through the admin content publish endpoint.
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("published_content", (table) => {
    table.increments("id").primary();
    table.string("slug", 400).notNullable().unique();
    table.text("title").notNullable();
    table.text("body").notNullable();
    table.text("meta_description").nullable();
    table.jsonb("faq_items").defaultTo("[]");
    table.string("category", 100).nullable();
    table.string("author_name", 200).nullable();
    table.string("status", 20).defaultTo("draft").notNullable();
    table.timestamp("published_at", { useTz: true }).nullable();
    table.timestamp("created_at", { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp("updated_at", { useTz: true }).defaultTo(knex.fn.now());
  });

  await knex.raw(
    "CREATE INDEX idx_published_content_slug ON published_content(slug)"
  );
  await knex.raw(
    "CREATE INDEX idx_published_content_status ON published_content(status)"
  );
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists("published_content");
}
